---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url:
sections:
- type: directory
  path: sander/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: sander/content/posts
  label: Posts
  create: all
  match: "**/*"
upload_dir: sander//static/uploads
public_path: "/uploads"
front_matter_path: 'sander/config.toml'
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -d public
  publish_command: hugo
  output_directory: public
version: '0.52'
